version: "3.8"

services:
  fast_api:
    networks:
      - main
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_microservice
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/fastapi-webtronics
  postgresql:
    image: postgres:14.7-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - main
    env_file:
      - .env

networks:
  main:
    driver: bridge
    name: main

volumes:
    postgres_data:
